import React,{useState}from'react';
import{Eye,EyeOff,Loader2,Lock,ShieldCheck}from'lucide-react';
import{AuthShell}from'../../components/auth/AuthShell';
import{useGym}from'../../context/GymContext';
import type{UserRole}from'../../types';

export const ChangeInitialPasswordPage:React.FC=()=>{
 const{setRole,navigate}=useGym();
 const[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[showPassword,setShowPassword]=useState(false),[showConfirm,setShowConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(password.length<10)return setError('Password must be at least 10 characters.');if(password!==confirm)return setError('Passwords do not match.');setBusy(true);setError('');try{const response=await fetch(`${import.meta.env.VITE_API_BASE_URL||'http://localhost:8080'}/api/v1/auth/change-initial-password`,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({password})});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body?.error?.message||'Unable to change password')}const role=sessionStorage.getItem('sarex.pendingRole')as UserRole|null;sessionStorage.removeItem('sarex.pendingRole');role?setRole(role):navigate('/login')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to change password')}finally{setBusy(false)}};
 const input=(label:string,value:string,setter:(value:string)=>void,visible:boolean,toggle:()=>void)=><label className="block text-xs font-bold">{label}<div className="relative mt-2"><Lock className="absolute left-4 top-4 h-4 w-4 text-gray-400"/><input type={visible?'text':'password'} required minLength={10} value={value} onChange={e=>setter(e.target.value)} className="h-12 w-full rounded-xl border bg-white pl-11 pr-12 text-sm outline-none focus:border-[#EF1B23] focus:ring-4 focus:ring-red-100/70" placeholder="At least 10 characters"/><button type="button" onClick={toggle} className="absolute right-4 top-4 text-gray-500" aria-label={visible?`Hide ${label}`:`Show ${label}`}>{visible?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></label>;
 return <AuthShell mode="login"><span className="text-[10px] font-black uppercase tracking-[.24em] text-[#EF1B23]">First sign-in security</span><h1 className="mt-3 text-4xl font-black tracking-tight">Create your private password</h1><p className="mt-2 text-sm leading-6 text-gray-500">Replace the temporary password supplied by your administrator.</p>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</div>}<form onSubmit={submit} className="mt-6 space-y-4">{input('New password',password,setPassword,showPassword,()=>setShowPassword(value=>!value))}{input('Confirm password',confirm,setConfirm,showConfirm,()=>setShowConfirm(value=>!value))}<button disabled={busy} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#EF1B23] text-sm font-black text-white">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<ShieldCheck className="h-4 w-4"/>}{busy?'Securing account…':'Save password and continue'}</button></form></AuthShell>;
};
