import React,{useState}from'react';
import{ArrowLeft,ArrowRight,Eye,EyeOff,Loader2,Lock,Mail}from'lucide-react';
import{useGym}from'../../context/GymContext';
import{AuthShell}from'../../components/auth/AuthShell';
import{GoogleAuthButton}from'../../components/auth/GoogleAuthButton';
import{apiUrl}from'../../lib/secureFetch';

export const LoginPage:React.FC=()=>{
 const{navigate,setRole}=useGym();
 const rememberedEmail=(()=>{try{return localStorage.getItem('sarex.rememberedEmail')||''}catch{return ''}})();
 const[email,setEmail]=useState(rememberedEmail),[password,setPassword]=useState(''),[remember,setRemember]=useState(Boolean(rememberedEmail)||true),[show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch(apiUrl('/api/v1/auth/login'),{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({email,password,remember})}),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error?.message||'Unable to sign in');try{if(remember)localStorage.setItem('sarex.rememberedEmail',email);else localStorage.removeItem('sarex.rememberedEmail')}catch{}const roles:string[]=b.user?.roles||[],selected=roles.includes('admin')?'super_admin':roles.includes('staff')?'staff':roles.includes('trainer')?'trainer':roles.includes('member')?'member':null;if(!selected)throw new Error('This account has no assigned application role');const requestedReturn=new URLSearchParams(location.search).get('returnTo');const returnTo=requestedReturn||(location.pathname==='/check-in/reception'?'/check-in/reception':null);if(b.user?.mustChangePassword){sessionStorage.setItem('sarex.pendingRole',selected);navigate('/change-password')}else if(returnTo?.startsWith('/')&&roles.includes('member'))navigate(returnTo);else setRole(selected);window.dispatchEvent(new CustomEvent('sarex:session-changed',{detail:{roles}}))}catch(reason){setError(reason instanceof Error?reason.message:'Unable to sign in')}finally{setBusy(false)}};
 return <AuthShell mode="login">
  <div className="mb-6"><h1 className="text-4xl font-black tracking-[-.04em] sm:text-5xl">Welcome back</h1><p className="mt-2 text-sm leading-6 text-[#6e6e73]">Sign in to manage your fitness journey.</p></div>
  {error&&<div role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-3.5 text-xs font-semibold text-red-700">{error}</div>}
  <form onSubmit={submit} className="space-y-4">
   <label className="block text-xs font-bold text-[#29292c]">Email address<div className="relative mt-2"><Mail className="absolute left-4 top-4 h-4 w-4 text-[#8a8a8f]"/><input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" className="h-12 w-full rounded-xl border border-[#d9d9d6] bg-white pl-11 pr-3 text-sm outline-none transition focus:border-[#EF1B23] focus:ring-4 focus:ring-red-100/70"/></div></label>
   <label className="block text-xs font-bold text-[#29292c]">Password<div className="relative mt-2"><Lock className="absolute left-4 top-4 h-4 w-4 text-[#8a8a8f]"/><input type={show?'text':'password'} autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" className="h-12 w-full rounded-xl border border-[#d9d9d6] bg-white pl-11 pr-12 text-sm outline-none transition focus:border-[#EF1B23] focus:ring-4 focus:ring-red-100/70"/><button type="button" onClick={()=>setShow(!show)} aria-label={show?'Hide password':'Show password'} className="absolute right-4 top-3.5 rounded-md p-1 text-[#777] hover:bg-gray-100">{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></label>
   <div className="flex items-center justify-between text-xs"><label className="flex cursor-pointer items-center gap-2.5 text-[#626267]"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)} className="h-4 w-4 accent-[#EF1B23]"/>Remember me</label><button type="button" onClick={()=>navigate('/forgot-password')} className="font-bold text-[#EF1B23] hover:underline">Forgot password?</button></div>
   <button disabled={busy} className="group flex h-[52px] w-full items-center justify-center gap-2 rounded-xl bg-[#EF1B23] text-sm font-black text-white shadow-[0_12px_30px_rgba(239,27,35,.2)] transition hover:bg-[#d9141c] disabled:opacity-60">{busy&&<Loader2 className="h-4 w-4 animate-spin"/>}{busy?'Signing in…':'Sign in'}{!busy&&<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/>}</button>
  </form>
  {import.meta.env.VITE_GOOGLE_CLIENT_ID&&<div className="mt-5">
   <div className="mb-3 flex items-center gap-3 text-[9px] font-bold uppercase tracking-[.18em] text-[#8a8a8f]"><span className="h-px flex-1 bg-[#dededa]"/>or continue with<span className="h-px flex-1 bg-[#dededa]"/></div>
   <GoogleAuthButton onError={setError} onResult={result=>{if(result.registration){sessionStorage.setItem('sarex.googleRegistration',JSON.stringify(result.registration));navigate('/register');return;}const roles=result.user?.roles||[];window.dispatchEvent(new CustomEvent('sarex:session-changed',{detail:{roles}}));const returnTo=location.pathname==='/check-in/reception'?'/check-in/reception':'/member/dashboard';navigate(returnTo);}}/>
  </div>}
  <div className="my-5 h-px bg-gray-200"/><p className="text-center text-xs text-[#69696d]">New to SAREX? <button onClick={()=>navigate('/register')} className="font-bold text-[#EF1B23] hover:underline">Create an account</button></p><button onClick={()=>navigate('/')} className="mt-3 w-full text-center text-xs font-bold text-gray-500 hover:text-[#EF1B23]"><ArrowLeft className="mr-1 inline h-3.5 w-3.5"/>Back to home</button>
 </AuthShell>;
};
