import React,{useState}from'react';
import{ArrowLeft,ArrowRight,Check,CreditCard,Eye,EyeOff,Loader2}from'lucide-react';
import{useGym}from'../../context/GymContext';
import{AuthShell}from'../../components/auth/AuthShell';
import{PaystackModal}from'../../components/ui/PaystackModal';
import{GoogleAuthButton}from'../../components/auth/GoogleAuthButton';
import{apiUrl}from'../../lib/secureFetch';

const field='mt-1 h-10 w-full rounded-xl border border-[#d9d9d6] bg-white px-3 text-sm outline-none transition focus:border-[#EF1B23] focus:ring-4 focus:ring-red-100/70 sm:mt-2 sm:h-12 sm:px-4';
const steps=['Details','Membership','Payment'];

export const RegisterPage:React.FC=()=>{
 const{plans,setRole,navigate}=useGym();
 const requestedPlanId=new URLSearchParams(location.search).get('plan')||'';
 const storedGoogle=(()=>{try{return JSON.parse(sessionStorage.getItem('sarex.googleRegistration')||'null')}catch{return null}})();
 const[step,setStep]=useState(1);
 const[googleRegistration,setGoogleRegistration]=useState<{token:string;profile:{firstName:string;lastName:string;email:string;picture:string}}|null>(storedGoogle);
 const[f,setF]=useState({firstName:storedGoogle?.profile?.firstName||'',lastName:storedGoogle?.profile?.lastName||'',email:storedGoogle?.profile?.email||'',phone:'',password:'',confirmPassword:'',membershipPlanId:requestedPlanId});
 const[showPassword,setShowPassword]=useState(false),[showConfirm,setShowConfirm]=useState(false),[error,setError]=useState(''),[member,setMember]=useState<{id:string;number:string}|null>(null),[checkoutOpen,setCheckoutOpen]=useState(false),[busyAction,setBusyAction]=useState<'pay'|'later'|null>(null);
 const set=(key:string,value:string|boolean)=>setF(current=>({...current,[key]:value}));
 const selectedPlan=plans.find(plan=>plan.id===f.membershipPlanId);
 const next=()=>{if(!f.firstName||!f.lastName||!f.email||!f.phone)return setError('Complete your personal details to continue');if(!googleRegistration&&f.password.length<10)return setError('Password must be at least 10 characters');if(!googleRegistration&&f.password!==f.confirmPassword)return setError('Passwords do not match');setError('');setStep(2)};
 const createAccount=async(intent:'pay'|'later')=>{if(intent==='pay'&&!selectedPlan)return setError('Choose a membership plan to continue to payment');setBusyAction(intent);setError('');try{const google=Boolean(googleRegistration),planId=f.membershipPlanId||undefined,response=await fetch(apiUrl(google?'/api/v1/auth/google/register':'/api/v1/auth/register'),{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(google?{token:googleRegistration!.token,phone:f.phone,gender:'Other',planId}:{firstName:f.firstName,lastName:f.lastName,email:f.email,phone:f.phone,password:f.password,gender:'Other',planId})}),body=await response.json();if(!response.ok)throw new Error(body?.error?.message||'Registration failed');sessionStorage.removeItem('sarex.googleRegistration');setMember({id:body.data.memberId,number:body.data.memberNumber});window.dispatchEvent(new CustomEvent('sarex:session-changed',{detail:{roles:['member']}}));if(intent==='pay'){setStep(3);setCheckoutOpen(true)}else setRole('member')}catch(reason){setError(reason instanceof Error?reason.message:'Registration failed')}finally{setBusyAction(null)}};
 const submit=async(event:React.FormEvent)=>{event.preventDefault();await createAccount('pay')};
 const passwordField=(label:string,key:'password'|'confirmPassword',visible:boolean,toggle:()=>void)=><label className="block text-[11px] font-bold sm:text-xs">{label}<div className="relative"><input required type={visible?'text':'password'} autoComplete="new-password" value={f[key]} onChange={e=>set(key,e.target.value)} className={`${field} pr-10`} placeholder={key==='password'?'At least 10 characters':'Repeat password'}/><button type="button" onClick={toggle} className="absolute right-3 top-3 text-gray-500 sm:top-4" aria-label={visible?`Hide ${label.toLowerCase()}`:`Show ${label.toLowerCase()}`}>{visible?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></label>;
 return <AuthShell mode="register">
  <header className="mb-3 text-center sm:mb-5 sm:text-left"><h1 className="text-[25px] font-black tracking-[-.04em] sm:text-4xl">{step===1?'Create your account':step===2?'Choose your membership':'Account created'}</h1></header>
  <div className="mb-4 flex items-start sm:mb-5">{steps.map((label,index)=>{const number=index+1,active=number===step,done=number<step;return <React.Fragment key={label}><div className="min-w-0 text-center"><span className={`mx-auto grid h-6 w-6 place-items-center rounded-full text-[9px] font-black sm:h-7 sm:w-7 sm:text-[10px] ${active||done?'bg-[#EF1B23] text-white':'bg-gray-200 text-gray-500'}`}>{done?<Check className="h-3 w-3"/>:number}</span><small className={`mt-1 block whitespace-nowrap text-[8px] font-bold sm:text-[9px] ${active?'text-[#EF1B23]':'text-gray-400'}`}>{label}</small></div>{index<2&&<span className={`mt-3 h-px flex-1 sm:mt-3.5 ${number<step?'bg-[#EF1B23]':'bg-gray-200'}`}/>}</React.Fragment>})}</div>
  {error&&<div role="alert" className="mb-3 rounded-xl border border-red-200 bg-red-50 p-2.5 text-xs font-semibold text-red-700">{error}</div>}

  {step===1&&<div className="space-y-2 sm:space-y-4">
   {googleRegistration&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-800"><strong>Google account verified</strong><span className="mt-1 block">{googleRegistration.profile.email}</span></div>}
   <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 sm:gap-4"><label className="text-[11px] font-bold sm:text-xs">First name<input required disabled={!!googleRegistration} autoComplete="given-name" value={f.firstName} onChange={e=>set('firstName',e.target.value)} className={field}/></label><label className="text-[11px] font-bold sm:text-xs">Last name<input required disabled={!!googleRegistration} autoComplete="family-name" value={f.lastName} onChange={e=>set('lastName',e.target.value)} className={field}/></label></div>
   <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 sm:gap-4"><label className="text-[11px] font-bold sm:text-xs">Email address<input required disabled={!!googleRegistration} type="email" autoComplete="email" value={f.email} onChange={e=>set('email',e.target.value)} className={field} placeholder="you@example.com"/></label><label className="text-[11px] font-bold sm:text-xs">Phone number<input required type="tel" autoComplete="tel" value={f.phone} onChange={e=>set('phone',e.target.value)} className={field} placeholder="Phone number"/></label></div>
   {!googleRegistration&&<div className="grid grid-cols-1 gap-2 sm:grid-cols-2 sm:gap-4">{passwordField('Password','password',showPassword,()=>setShowPassword(value=>!value))}{passwordField('Confirm password','confirmPassword',showConfirm,()=>setShowConfirm(value=>!value))}</div>}
   <button type="button" onClick={next} className="flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#EF1B23] text-sm font-black text-white shadow-[0_12px_30px_rgba(239,27,35,.2)] sm:h-[52px]">Continue <ArrowRight className="h-4 w-4"/></button>
   {!googleRegistration&&import.meta.env.VITE_GOOGLE_CLIENT_ID&&<div className="pt-1">
    <div className="mb-3 flex items-center gap-3 text-[9px] font-bold uppercase tracking-[.18em] text-[#8a8a8f]"><span className="h-px flex-1 bg-[#dededa]"/>or continue with<span className="h-px flex-1 bg-[#dededa]"/></div>
    <GoogleAuthButton text="signup_with" onError={setError} onResult={result=>{if(result.user){window.dispatchEvent(new CustomEvent('sarex:session-changed',{detail:{roles:result.user.roles}}));navigate('/member/dashboard');return;}if(result.registration){setGoogleRegistration(result.registration);sessionStorage.setItem('sarex.googleRegistration',JSON.stringify(result.registration));setF(current=>({...current,...result.registration!.profile}));setError('');}}}/>
   </div>}
   <button type="button" onClick={()=>navigate('/login')} className="w-full py-1 text-center text-xs font-bold text-gray-500 hover:text-[#EF1B23]"><ArrowLeft className="mr-1 inline h-3.5 w-3.5"/>Back to login</button>
  </div>}

  {step===2&&<form onSubmit={submit}><p className="mb-3 text-xs leading-5 text-gray-500 sm:mb-4 sm:text-sm">Choose a membership if you want to pay now, or create your account and select a plan later from your portal.</p><div className="max-h-[31vh] space-y-2 overflow-y-auto pr-1 sm:max-h-[300px]">{plans.filter(plan=>plan.isActive!==false).map(plan=><button key={plan.id} type="button" onClick={()=>set('membershipPlanId',plan.id)} className={`flex w-full items-center justify-between rounded-xl border p-3 text-left transition sm:p-4 ${f.membershipPlanId===plan.id?'border-[#EF1B23] bg-red-50 ring-2 ring-red-100':'border-gray-200 bg-white'}`}><span><strong className="block text-xs sm:text-sm">{plan.name}</strong><small className="mt-1 block text-[10px] text-gray-500">{plan.durationDays} days · {plan.description}</small><small className="mt-1 block text-[10px] font-semibold text-emerald-700">{[plan.workoutPlanAccess?'Workout plans':null,plan.trainerAccess?'Trainer access':null].filter(Boolean).join(' · ')}</small></span><span className="ml-3 text-right"><strong className="block whitespace-nowrap text-xs text-[#EF1B23] sm:text-sm">₦{(plan.price+(plan.registrationFee||0)).toLocaleString()}</strong><small className="mt-0.5 block whitespace-nowrap text-[9px] text-gray-400">Membership: ₦{plan.price.toLocaleString()}</small>{Boolean(plan.registrationFee)&&<small className="block whitespace-nowrap text-[9px] text-gray-500">Registration: ₦{(plan.registrationFee||0).toLocaleString()}</small>}</span></button>)}</div><div className="mt-3 grid grid-cols-[auto_minmax(0,1fr)] gap-3 sm:grid-cols-[auto_minmax(0,1fr)_minmax(0,1fr)]"><button type="button" onClick={()=>setStep(1)} disabled={Boolean(busyAction)} className="grid h-11 w-12 place-items-center rounded-xl border bg-white disabled:opacity-50 sm:h-[52px] sm:w-14"><ArrowLeft className="h-4 w-4"/></button><button disabled={Boolean(busyAction)||!selectedPlan} className="flex h-11 min-w-0 items-center justify-center gap-2 rounded-xl bg-[#EF1B23] px-3 text-xs font-black text-white disabled:opacity-50 sm:h-[52px] sm:text-sm">{busyAction==='pay'?<Loader2 className="h-4 w-4 animate-spin"/>:<CreditCard className="h-4 w-4"/>}{busyAction==='pay'?'Creating account…':'Continue to payment'}</button><button type="button" onClick={()=>createAccount('later')} disabled={Boolean(busyAction)} className="col-span-2 h-11 rounded-xl border border-gray-300 px-3 text-xs font-bold text-gray-700 disabled:opacity-50 sm:col-span-1 sm:h-[52px] sm:text-sm">{busyAction==='later'?'Creating account…':'Pay later'}</button></div></form>}

  {step===3&&member&&selectedPlan&&<div className="text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-emerald-50 text-emerald-600 sm:h-16 sm:w-16"><Check className="h-7 w-7"/></div><p className="mt-3 text-xs leading-5 text-gray-500 sm:text-sm">Complete payment to activate your membership and reception check-in access.</p><div className="mt-4 rounded-xl border bg-white p-3 text-left sm:p-4"><small className="font-bold uppercase tracking-wider text-gray-400">Selected membership</small><div className="mt-2 flex justify-between gap-4"><strong>{selectedPlan.name}</strong><strong className="text-[#EF1B23]">₦{(selectedPlan.price + (selectedPlan.registrationFee || 0)).toLocaleString()}</strong></div>{Boolean(selectedPlan.registrationFee) && <p className="mt-2 text-[10px] text-gray-500">Includes a one-time registration fee of ₦{(selectedPlan.registrationFee || 0).toLocaleString()}</p>}</div><button onClick={()=>setCheckoutOpen(true)} className="mt-4 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#EF1B23] text-xs font-black text-white sm:h-[52px] sm:text-sm"><CreditCard className="h-4 w-4"/>Pay and activate membership</button><button onClick={()=>setRole('member')} className="mt-2 h-10 w-full rounded-xl border text-xs font-bold">Pay later and continue</button><button onClick={()=>setStep(2)} className="mt-2 text-xs font-bold text-gray-500"><ArrowLeft className="mr-1 inline h-3.5 w-3.5"/>Back to membership</button><PaystackModal isOpen={checkoutOpen} onClose={()=>setCheckoutOpen(false)} plan={selectedPlan} memberName={`${f.firstName} ${f.lastName}`} memberId={member.id} isNewMember onSuccess={()=>{}}/></div>}
 </AuthShell>;
};
