import React,{useState}from'react';
import{CheckCircle2,Eye,EyeOff,Loader2,Lock}from'lucide-react';
import{useGym}from'../../context/GymContext';
import{AuthShell}from'../../components/auth/AuthShell';

export const ResetPasswordPage:React.FC=()=>{
 const{navigate}=useGym();
 const[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[showPassword,setShowPassword]=useState(false),[showConfirm,setShowConfirm]=useState(false),[done,setDone]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(password.length<10)return setError('Password must be at least 10 characters');if(password!==confirm)return setError('Passwords do not match');const token=new URLSearchParams(location.search).get('token');if(!token)return setError('This reset link is missing its security token. Request a new link.');setBusy(true);setError('');try{const response=await fetch(`${import.meta.env.VITE_API_BASE_URL||''}/api/v1/auth/reset-password`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password})});if(!response.ok){const body=await response.json();throw new Error(body?.error?.message||'Unable to reset password')}setDone(true)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to reset password')}finally{setBusy(false)}};
 const input=(label:string,value:string,setter:(value:string)=>void,visible:boolean,toggle:()=>void)=><label className="block text-xs font-bold">{label}<div className="relative mt-2"><Lock className="absolute left-4 top-4 h-4 w-4 text-gray-400"/><input type={visible?'text':'password'} required value={value} onChange={e=>setter(e.target.value)} className="h-12 w-full rounded-xl border bg-white pl-11 pr-12 text-sm outline-none focus:border-[#EF1B23] focus:ring-4 focus:ring-red-100/70" placeholder="At least 10 characters"/><button type="button" onClick={toggle} className="absolute right-4 top-4 text-gray-500" aria-label={visible?`Hide ${label}`:`Show ${label}`}>{visible?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></label>;
 return <AuthShell mode="login">{done?<div className="text-center"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-600"/><h1 className="mt-4 text-3xl font-black">Password updated</h1><p className="mt-3 text-sm text-gray-500">Sign in again with your new password.</p><button onClick={()=>navigate('/login')} className="mt-7 h-12 w-full rounded-xl bg-[#EF1B23] text-sm font-black text-white">Sign in now</button></div>:<><span className="text-[10px] font-black uppercase tracking-[.24em] text-[#EF1B23]">Secure reset</span><h1 className="mt-3 text-4xl font-black tracking-tight">Set a new password</h1><p className="mt-2 text-sm text-gray-500">Choose a strong password for your account.</p>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</div>}<form onSubmit={submit} className="mt-6 space-y-4">{input('New password',password,setPassword,showPassword,()=>setShowPassword(value=>!value))}{input('Confirm new password',confirm,setConfirm,showConfirm,()=>setShowConfirm(value=>!value))}<button disabled={busy} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#EF1B23] text-sm font-black text-white">{busy&&<Loader2 className="h-4 w-4 animate-spin"/>}{busy?'Updating password…':'Save new password'}</button></form><button onClick={()=>navigate('/forgot-password')} className="mt-5 w-full text-xs font-bold text-[#EF1B23]">Request a different reset link</button></>}</AuthShell>;
};
