import React,{useState}from'react';
import{Calendar,Check,CreditCard,Printer,ShieldCheck}from'lucide-react';
import{useGym}from'../../context/GymContext';
import{AppLayout}from'../../components/layout/AppLayout';
import{Badge}from'../../components/ui/Badge';
import{Modal}from'../../components/ui/Modal';
import{PaystackModal}from'../../components/ui/PaystackModal';
import{PaymentReceipt}from'../../components/ui/PaymentReceipt';
import type{MembershipPlan,PaymentRecord}from'../../types';

export const MemberMembership:React.FC=()=>{
 const{currentMember,plans,payments}=useGym();
 const[selectedPlan,setSelectedPlan]=useState<MembershipPlan|null>(null),[checkoutOpen,setCheckoutOpen]=useState(false),[selectedReceipt,setSelectedReceipt]=useState<PaymentRecord|null>(null);
 if(!currentMember)return <><PaymentReceipt/><AppLayout pageTitle="Membership Details"><div className="rounded-lg border bg-white p-8 text-center">No member profile active.</div></AppLayout></>;
 const myPayments=payments.filter(payment=>payment.memberId===currentMember.memberId||payment.memberName.includes(currentMember.firstName));
 const hasSubscription=Boolean(currentMember.membershipPlanId||currentMember.membershipPlanName&&currentMember.membershipPlanName!=='No active plan');
 const hasActiveSubscription=currentMember.membershipStatus==='Active'&&Boolean(currentMember.membershipExpiryDate)&&new Date(currentMember.membershipExpiryDate)>new Date();
 const currentPlan=plans.find(plan=>plan.id===currentMember.membershipPlanId)||null;
 const summaryPlan=hasSubscription?(currentPlan||({name:currentMember.membershipPlanName,id:currentMember.membershipPlanId}as MembershipPlan)):selectedPlan;
 const summaryStatus=hasSubscription?(currentMember.membershipStatus||currentMember.status):selectedPlan?'Selected':'Not selected';
 const statusVariant=hasActiveSubscription?'success':selectedPlan&&!hasSubscription?'warning':'danger';
 const selectedIsDifferentPlan=Boolean(selectedPlan&&hasActiveSubscription&&selectedPlan.id!==currentMember.membershipPlanId);
 return <><PaymentReceipt/><AppLayout pageTitle="Membership Subscription & Billing" pageSubtitle="View your subscription status, select a membership, renew securely, and review payment history.">
  <div className="grid grid-cols-1 gap-6 lg:grid-cols-12">
   <section className="rounded-xl border border-[#E5E7EB] bg-white p-5 shadow-sm lg:col-span-4">
    <span className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-gray-400">{hasSubscription?'Subscription':'Selected subscription'}</span>
    <div className="mb-4 flex items-start justify-between gap-3"><h3 className="text-2xl font-bold uppercase text-[#111]">{summaryPlan?.name||'Choose a membership'}</h3><Badge variant={statusVariant as any}>{String(summaryStatus)}</Badge></div>
    {summaryPlan&&'price'in summaryPlan&&summaryPlan.price!==undefined&&<div className="mb-4 rounded-lg bg-gray-50 p-3"><strong className="text-lg text-[#EF1B23]">₦{summaryPlan.price.toLocaleString()}</strong><span className="ml-2 text-xs text-gray-500">for {summaryPlan.durationDays} days</span></div>}
    <div className="space-y-3 text-xs"><div className="flex justify-between border-b border-gray-100 py-2"><span className="text-gray-500">Member ID</span><span className="font-mono font-bold">{currentMember.memberId}</span></div><div className="flex justify-between border-b border-gray-100 py-2"><span className="text-gray-500">Enrolled On</span><span className="font-semibold">{hasSubscription&&currentMember.membershipStartDate?currentMember.membershipStartDate:'—'}</span></div><div className="flex justify-between border-b border-gray-100 py-2"><span className="text-gray-500">Expires On</span><span className="font-mono font-bold text-[#EF1B23]">{hasSubscription&&currentMember.membershipExpiryDate?currentMember.membershipExpiryDate:'—'}</span></div>{currentMember.nextPlanName&&<><div className="flex justify-between border-b border-gray-100 py-2"><span className="text-gray-500">Next plan</span><span className="font-bold text-sky-700">{currentMember.nextPlanName}</span></div><div className="flex justify-between border-b border-gray-100 py-2"><span className="text-gray-500">Scheduled start</span><span className="font-mono font-bold">{currentMember.nextPlanStartDate||'—'}</span></div></>}<div className="flex justify-between py-2"><span className="text-gray-500">Entrance access</span><span className={`flex items-center gap-1 font-bold ${hasActiveSubscription?'text-emerald-600':'text-gray-400'}`}><ShieldCheck className="h-3.5 w-3.5"/>{hasActiveSubscription?'Active':'Inactive'}</span></div></div>
    {selectedIsDifferentPlan&&<div className="mt-4 rounded-lg border border-sky-200 bg-sky-50 p-3 text-xs font-semibold text-sky-800">Your new plan will start when your current plan ends.</div>}
    <button onClick={()=>selectedPlan&&setCheckoutOpen(true)} disabled={!selectedPlan} className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg bg-[#EF1B23] py-3 text-xs font-bold uppercase tracking-wider text-white disabled:bg-gray-200 disabled:text-gray-400"><CreditCard className="h-4 w-4"/>{selectedIsDifferentPlan?'Schedule selected plan':hasActiveSubscription?'Renew selected plan':'Activate selected plan'}</button>
   </section>
   <section className="rounded-xl border border-[#E5E7EB] bg-white p-5 shadow-sm lg:col-span-8"><h3 className="text-base font-bold uppercase tracking-wider">Select membership plan</h3><p className="mb-4 mt-1 text-xs text-gray-500">Choose a plan to update the selected subscription summary.</p><div className="grid grid-cols-1 gap-4 sm:grid-cols-2">{plans.filter(plan=>plan.isActive!==false).map(plan=>{const chosen=selectedPlan?.id===plan.id;return <button type="button" key={plan.id} onClick={()=>setSelectedPlan(plan)} className={`rounded-lg border-2 p-4 text-left transition ${chosen?'border-[#EF1B23] bg-red-50/30':'border-[#E5E7EB] hover:border-gray-300'}`}><div className="flex items-center justify-between"><strong className="text-sm uppercase">{plan.name}</strong><span className="text-[10px] text-gray-500">{plan.durationDays} Days</span></div><div className="mt-2 text-xl font-bold text-[#EF1B23]">₦{plan.price.toLocaleString()}</div><p className="mt-1 min-h-[30px] text-[11px] text-gray-500">{plan.description}</p><div className="mt-2 space-y-1 border-t border-gray-100 pt-2 text-[11px] text-gray-600">{plan.features.slice(0,2).map(feature=><div key={feature} className="flex items-center gap-1.5"><Check className="h-3 w-3 shrink-0 text-[#EF1B23]"/><span>{feature}</span></div>)}</div></button>})}</div></section>
  </div>

  <section className="mt-6 w-full overflow-hidden rounded-xl border border-[#E5E7EB] bg-white shadow-sm"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-4"><div><h3 className="text-base font-bold uppercase tracking-wider">Payment History</h3><p className="mt-1 text-xs text-gray-500">All membership payments and receipt references.</p></div><Calendar className="h-5 w-5 text-gray-400"/></div>{myPayments.length===0?<div className="px-5 py-14 text-center text-sm text-gray-500">No payment history yet.</div>:<div className="w-full overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-gray-50 text-[10px] uppercase tracking-wider text-gray-500"><tr><th className="px-5 py-3">Date</th><th className="px-5 py-3">Membership plan</th><th className="px-5 py-3">Reference</th><th className="px-5 py-3">Method</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Receipt</th></tr></thead><tbody className="divide-y divide-gray-100">{myPayments.map(payment=><tr key={payment.id} className="hover:bg-gray-50/70"><td className="whitespace-nowrap px-5 py-4">{new Date(payment.date).toLocaleDateString()}</td><td className="px-5 py-4 font-bold">{payment.planName}</td><td className="px-5 py-4 font-mono text-[10px] text-gray-500">{payment.transactionReference||payment.reference}</td><td className="px-5 py-4">{payment.paymentMethod||payment.method||'—'}</td><td className="px-5 py-4 font-bold">₦{payment.amount.toLocaleString()}</td><td className="px-5 py-4"><Badge variant={payment.status==='Successful'?'success':'warning'}>{payment.status}</Badge></td><td className="px-5 py-4 text-right"><button onClick={()=>setSelectedReceipt(payment)} className="inline-flex items-center gap-1 rounded-lg bg-gray-100 px-3 py-2 font-bold hover:bg-gray-200"><Printer className="h-3.5 w-3.5"/>View</button></td></tr>)}</tbody></table></div>}</section>

  {selectedPlan&&<PaystackModal isOpen={checkoutOpen} onClose={()=>setCheckoutOpen(false)} plan={selectedPlan} memberName={`${currentMember.firstName} ${currentMember.lastName}`} memberId={currentMember.id} isNewMember={!currentMember.registrationFeePaid} onSuccess={()=>setCheckoutOpen(false)}/>} 
  {selectedReceipt&&<Modal isOpen onClose={()=>setSelectedReceipt(null)} title="OFFICIAL RECEIPT" subtitle="SAREX Fitness Clinic" maxWidth="sm"><div className="space-y-2 rounded-lg border bg-gray-50 p-4 font-mono text-xs"><div className="border-b pb-2 text-center font-bold">SAREX FITNESS CLINIC</div><div className="flex justify-between"><span>Reference</span><span>{selectedReceipt.transactionReference||selectedReceipt.reference}</span></div><div className="flex justify-between"><span>Plan</span><span>{selectedReceipt.planName}</span></div><div className="flex justify-between"><span>Date</span><span>{new Date(selectedReceipt.date).toLocaleDateString()}</span></div><div className="flex justify-between border-t pt-2 text-sm font-bold"><span>Paid</span><span className="text-[#EF1B23]">₦{selectedReceipt.amount.toLocaleString()}</span></div></div><button onClick={()=>window.print()} className="mt-4 w-full rounded-lg bg-[#EF1B23] py-2.5 text-xs font-bold uppercase text-white">Print or save receipt</button></Modal>}
 </AppLayout></>;
};
